export var Setting: typeof import("./_Setting").Setting;
export var Antialias: typeof import("./Antialias").Antialias;
export var Background: typeof import("./Background").Background;
export var Fill: typeof import("./Fill").Fill;
export var Colorspace: typeof import("./Colorspace").Colorspace;
export var ColorspaceType: {
    CMY: string;
    CMYK: string;
    Gray: string;
    HCL: string;
    HCLp: string;
    HSB: string;
    HSI: string;
    HSL: string;
    HSV: string;
    HWB: string;
    Jzazbz: string;
    Lab: string;
    LCHab: string;
    LCHuv: string;
    LMS: string;
    Log: string;
    Luv: string;
    OHTA: string;
    Rec601YCbCr: string;
    Rec709YCbCr: string;
    RGB: string;
    scRGB: string;
    sRGB: string;
    Transparent: string;
    xyY: string;
    XYZ: string;
    YCbCr: string;
    YCC: string;
    YDbDr: string;
    YIQ: string;
    YPbPr: string;
    YUV: string;
    Undefined: string;
};
export var Font: typeof import("./Font").Font;
export var Format: typeof import("./Format").Format;
export var Gravity: typeof import("./Gravity").Gravity;
export var GravityType: {
    None: string;
    Center: string;
    East: string;
    Forget: string;
    NorthEast: string;
    North: string;
    NorthWest: string;
    SouthEast: string;
    South: string;
    SouthWest: string;
    West: string;
};
export var Interlace: typeof import("./Interlace").Interlace;
export var InterlaceType: {
    none: string;
    line: string;
    plane: string;
    partition: string;
    JPEG: string;
    GIF: string;
    PNG: string;
};
export var Monitor: typeof import("./Monitor").Monitor;
export var Quality: typeof import("./Quality").Quality;
export var Pointsize: typeof import("./Pointsize").Pointsize;
export var Size: typeof import("./Size").Size;
